export chooseImage from './chooseImage'
export closeWindow from './closeWindow'
export getLocation from './getLocation'
export { scanQRCode } from './qrCode'
export selectPeoples from './selectPeoples'
export previewImage from './previewImage'
